const i18n = {
  kk: {
    // index
    btnLogin: "Кіру",
    btnRegister: "Тіркелу",
    // login / register
    phonePh: "Телефон нөмірі",
    emailPh: "Email",
    passwordPh: "Құпиясөз",
    loginBtn: "Кіру",
    btnBack: "← Артқа",
    firstNamePh: "Аты",
    lastNamePh: "Тегі",
    passwordRegPh: "Оқу платформасына арналған құпиясөз",
    password2Ph: "Құпиясөзді қайталаңыз",
    submitBtn: "Тіркелу",
    // dashboard static
    dashSub: "Студент Кабинеті",
    btnCourse: "📚 Курсқа өту",
    btnRefresh: "🔄 Жаңарту",
    btnLogout: "🚪 Шығу",
    headline: "Бұл сенің жеке кабинетің.",
    headlineDesc: "Бізбен бірге алған білім арқылы үлкен белестерді бағындыр.",
    todayPlan: "🗓 Бүгінгі жоспар",
    todayLabel: "Бүгін қай тақырыпты оқитыныңды жаз",
    todayPh: "Мысалы: Рационал сандар, теңдеулер, үшбұрыштар...",
    todayNote: "* Барлық тапсырманы толық орындағаннан кейін ғана белгі қойыңыз.",
    analytics: "📈 Аналитика",
    kpiAvgLab: "Орташа баға",
    kpiDoneLab: "Бағаланған сабақ",
    kpiGoalLab: "Жалпы прогресс",
    last10: "Соңғы 10 баға",
    recentGrades: "🏅 Соңғы бағалар",
    achievements: "🏆 Жетістіктер",
    notifications: "🔔 Хабарламалар",
    notifNote: "Жаңа баға/файл/мақсат — осында шығады.",
    teacherFb: "💬 Мұғалім пікірі",
    profileSupport: "👤 Профиль және қолдау",
    copyIdBtn: "🧾 Student ID көшіру",
    copiedMsg: "Student ID көшірілді ✅",
    avatarHint: "* Аватарды бас → өз фотоңды таңда",
    // dashboard dynamic
    greetingAdmin: "Сәлем, Admin 👋",
    greetingStudent: "Сәлем, оқушы! 👋",
    noFeedback: "Әзірге мұғалім пікірі жоқ",
    pkgPrefix: "Пакет: ",
    // admin
    adminSub: "Admin панель",
    studentsTitle: "👥 Оқушылар тізімі",
    reloadTitle: "Жаңарту",
    reloadSub: "Оқушыларды қайта жүктеу",
    uploadTitle: "📦 Материал жүктеу",
    courseLabel: "Курс",
    courseSub: "База / Стандарт / Премиум",
    videosLabel: "Видеолар",
    videosFmt: "mp4 / mov / webm",
    audiosLabel: "Аудиолар",
    audiosFmt: "mp3 / wav / etc",
    docsLabel: "Документтер",
    docsFmt: "pdf / doc / docx",
    fbTitle: "💬 Мұғалім пікірі",
    fbSub: "Оқушыға көрінетін комментарий",
    fbPh: "Мысалы: Тапсырма жақсы, бірақ дәлелдеуді толық жаз.",
    saveTitle: "Сақтау",
    saveSub: "Блок нөмірін сұрайды (1-100)",
    saveBtn: "✅ Жүктеу",
    saveNote: "Кеңес: жүктеп болған соң сабақ бетіне өтесің, тексеріп көресің.",
    notAdmin: "Admin емес!",
    // my-courses
    courses: "Менің курстарым",
    // course pages
    lessonLabel: "Сабақ",
    btnVideo: "Видеоны көру",
    btnDoc: "Тапсырманы ашу",
    btnQuiz: "Сынақты ашу",
    btnAI: "ЖИ қолдану",
    btnUpload: "Тапсырма жүктеу",
    btnMine: "Менің тапсырмам",
    btnStudentTask: "Оқушы тапсырмасы",
    btnGrade: "Баға қою",
    gradeUnit: "сынып",
    noVideo: "Видео жоқ",
    noDoc: "Тапсырма жоқ",
    noUpload: "Сен бұл сабаққа әлі тапсырма жүктемедің",
    noStudentTask: "Бұл сабаққа тапсырма жоқ",
    noStudentTaskPreview: "Бұл оқушыдан бұл сабаққа тапсырма жоқ",
    uploadSuccess: "✅ Тапсырма жүктелді!",
    uploadFail: "Жүктелмеді",
    uploadErr: "Қате: ",
    taskOpenFail: "Тапсырма ашылмады",
    quizTitle: "Сынақ",
    quizDesc: "Сынақ жақында қосылады.",
    aiTitle: "ЖИ Көмекшісі",
    aiDesc: "ЖИ көмекшісі жақында қосылады.",
    closeBtn: "Жабу",
    courseBase: "Менің курстарым — База",
    courseStandard: "Менің курстарым — Стандарт",
    coursePremium: "Менің курстарым — Премиум",
    breadBase: "# База курс",
    breadStandard: "# Стандарт курс",
    breadPremium: "# Премиум курс",
    // dashboard dynamic strings
    checkVideo: "Видео көру",
    checkUpload: "Тапсырма жүктеу",
    checkTest: "Тақырып аралық сынақтардан өту",
    checkAI: "ЖИ қолдану",
    statusFeedback: "💬 Фидбек бар",
    statusGraded: "🏅 Баға қойылды",
    statusReviewing: "🕒 Тексерілуде",
    statusChecked: "✅ Тексерілді",
    statusUploaded: "📤 Жүктелді",
    statusNotUploaded: "❌ Жүктелмеген",
    noGradesYet: "Әзірге баға жоқ",
    noGradesYetSub: "Admin баға қойған кезде көрінеді.",
    achStreak: "🔥 Күндік серия",
    achStreakDesc: "күн қатарынан кірдің",
    achTask: "📤 Тапсырма",
    achTaskDesc: "рет тапсырма жібердің",
    achBest: "📅 Үздік деңгей",
    achBestDesc: "Осы айда өткен сабақтар саны",
    noNotif: "Әзірге хабарлама жоқ",
    noNotifSub: "Баға/файл болғанда осында шығады.",
    notifFailed: "Хабарламалар алынбады",
    serverError: "сервер байланыспады",
    student: "Оқушы",
    adminUpload: "Материал жүктеу / тексеру",
    pkgPending: "Пакет әлі бекітілмеді",
    // AI helper modal
    aiModalTitle: "GoTAB ЖИ қолдану",
    aiModalLoading: "Есептер дайындалуда…",
    aiModalError: "Қате болды. Қайта көріңіз.",
    aiBackBtn: "← Артқа",
    aiQuotaError: "AI сервисі қазір бос емес. 1–2 минуттан кейін қайталаңыз.",
    aiGeminiRateLimit: "AI сервисі қазір бос емес. 1–2 минуттан кейін қайталаңыз.",
    aiRateLimit: "OpenAI сұраныс лимиті уақытша асып кетті. Кейінірек қайталаңыз.",
    aiNoCredit: "OpenAI API credit әлі қосылмаған. Credit қосылғаннан кейін ЖИ жұмыс істейді.",
    aiNoKey: "OpenAI API key configured емес.",
    aiAction1: "📘 Бүгінгі тақырып бойынша 5 жаттығу есеп",
    aiAction2: "🔥 5 қиын есеп",
    aiAction3: "🧠 Аралас қайталау есептері",
    aiAction4: "🎯 Емтихан форматындағы есептер",
    aiUsageBar: "Бүгін: {used}/{limit} рет пайдаланылды",
    aiDailyLimit: "Бүгін осы сабақ бойынша лимитке жеттіңіз. Ертең қайта көріңіз.",
  },
  ru: {
    // index
    btnLogin: "Вход",
    btnRegister: "Регистрация",
    // login / register
    phonePh: "Номер телефона",
    emailPh: "Email",
    passwordPh: "Пароль",
    loginBtn: "Вход",
    btnBack: "← Назад",
    firstNamePh: "Имя",
    lastNamePh: "Фамилия",
    passwordRegPh: "Придумайте пароль для платформы",
    password2Ph: "Повторите пароль",
    submitBtn: "Зарегистрироваться",
    // dashboard static
    dashSub: "Личный кабинет",
    btnCourse: "📚 Перейти к курсу",
    btnRefresh: "🔄 Обновить",
    btnLogout: "🚪 Выйти",
    headline: "Это твой личный кабинет.",
    headlineDesc: "С нами достигай больших вершин через знания.",
    todayPlan: "🗓 План на сегодня",
    todayLabel: "Напиши тему, которую изучаешь сегодня",
    todayPh: "Например: Рациональные числа, уравнения, треугольники...",
    todayNote: "* Ставь галочку только после полного выполнения задания.",
    analytics: "📈 Аналитика",
    kpiAvgLab: "Средняя оценка",
    kpiDoneLab: "Оценённых уроков",
    kpiGoalLab: "Общий прогресс",
    last10: "Последние 10 оценок",
    recentGrades: "🏅 Последние оценки",
    achievements: "🏆 Достижения",
    notifications: "🔔 Уведомления",
    notifNote: "Новая оценка/файл/цель — появится здесь.",
    teacherFb: "💬 Отзыв учителя",
    profileSupport: "👤 Профиль и поддержка",
    copyIdBtn: "🧾 Скопировать Student ID",
    copiedMsg: "Student ID скопирован ✅",
    avatarHint: "* Нажми на аватар → выбери свою фотографию",
    // dashboard dynamic
    greetingAdmin: "Привет, Admin 👋",
    greetingStudent: "Привет! 👋",
    noFeedback: "Пока нет отзыва от учителя",
    pkgPrefix: "Пакет: ",
    // admin
    adminSub: "Панель администратора",
    studentsTitle: "👥 Список учеников",
    reloadTitle: "Обновить",
    reloadSub: "Перезагрузить список учеников",
    uploadTitle: "📦 Загрузка материалов",
    courseLabel: "Курс",
    courseSub: "База / Стандарт / Премиум",
    videosLabel: "Видео",
    videosFmt: "mp4 / mov / webm",
    audiosLabel: "Аудио",
    audiosFmt: "mp3 / wav / etc",
    docsLabel: "Документы",
    docsFmt: "pdf / doc / docx",
    fbTitle: "💬 Отзыв учителя",
    fbSub: "Комментарий, видимый ученику",
    fbPh: "Например: Задание хорошее, но пропиши доказательство полностью.",
    saveTitle: "Сохранить",
    saveSub: "Запрашивает номер блока (1-100)",
    saveBtn: "✅ Загрузить",
    saveNote: "Совет: после загрузки перейди на страницу урока и проверь.",
    notAdmin: "Не администратор!",
    // my-courses
    courses: "Мои курсы",
    // course pages
    lessonLabel: "Урок",
    btnVideo: "Смотреть видео",
    btnDoc: "Открыть задание",
    btnQuiz: "Открыть тест",
    btnAI: "Использовать ИИ",
    btnUpload: "Загрузить задание",
    btnMine: "Моё задание",
    btnStudentTask: "Задание ученика",
    btnGrade: "Поставить оценку",
    gradeUnit: "класс",
    noVideo: "Видео нет",
    noDoc: "Задание не найдено",
    noUpload: "Ты ещё не загружал задание к этому уроку",
    noStudentTask: "К этому уроку нет задания",
    noStudentTaskPreview: "От этого ученика нет задания к уроку",
    uploadSuccess: "✅ Задание загружено!",
    uploadFail: "Не загружено",
    uploadErr: "Ошибка: ",
    taskOpenFail: "Не удалось открыть задание",
    quizTitle: "Тест",
    quizDesc: "Тест скоро будет добавлен.",
    aiTitle: "ИИ Помощник",
    aiDesc: "ИИ помощник скоро будет добавлен.",
    closeBtn: "Закрыть",
    courseBase: "Мои курсы — Базовый",
    courseStandard: "Мои курсы — Стандарт",
    coursePremium: "Мои курсы — Премиум",
    breadBase: "# Базовый курс",
    breadStandard: "# Стандартный курс",
    breadPremium: "# Премиум курс",
    // dashboard dynamic strings
    checkVideo: "Смотреть видео",
    checkUpload: "Загрузить задание",
    checkTest: "Межтематические тесты",
    checkAI: "Использовать ИИ",
    statusFeedback: "💬 Есть отзыв",
    statusGraded: "🏅 Оценка поставлена",
    statusReviewing: "🕒 На проверке",
    statusChecked: "✅ Проверено",
    statusUploaded: "📤 Загружено",
    statusNotUploaded: "❌ Не загружено",
    noGradesYet: "Оценок пока нет",
    noGradesYetSub: "Появится когда Admin поставит оценку.",
    achStreak: "🔥 Дневная серия",
    achStreakDesc: "дней подряд заходишь",
    achTask: "📤 Задание",
    achTaskDesc: "раз загрузил задание",
    achBest: "📅 Лучший уровень",
    achBestDesc: "Уроков завершено в этом месяце",
    noNotif: "Уведомлений пока нет",
    noNotifSub: "Появится при новой оценке/файле.",
    notifFailed: "Уведомления не загружены",
    serverError: "сервер недоступен",
    student: "Ученик",
    adminUpload: "Загрузка / проверка материалов",
    pkgPending: "Пакет ещё не подтверждён",
    // AI helper modal
    aiModalTitle: "GoTAB ИИ помощник",
    aiModalLoading: "Готовим задачи…",
    aiModalError: "Произошла ошибка. Попробуйте ещё раз.",
    aiBackBtn: "← Назад",
    aiQuotaError: "AI сервис временно недоступен. Повторите через 1–2 минуты.",
    aiGeminiRateLimit: "AI сервис временно недоступен. Повторите через 1–2 минуты.",
    aiRateLimit: "Лимит запросов OpenAI временно превышен. Повторите позже.",
    aiNoCredit: "OpenAI API credit ещё не подключён. ИИ заработает после пополнения баланса.",
    aiNoKey: "OpenAI API key не настроен.",
    aiAction1: "📘 5 практических задач по теме",
    aiAction2: "🔥 5 сложных задач",
    aiAction3: "🧠 Смешанное повторение",
    aiAction4: "🎯 Задачи в формате экзамена",
    aiUsageBar: "Сегодня: {used}/{limit} использовано",
    aiDailyLimit: "Сегодня лимит по этому уроку исчерпан. Возвращайтесь завтра.",
  }
};

function applyLang(lang) {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (i18n[lang]?.[key] !== undefined) el.textContent = i18n[lang][key];
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (i18n[lang]?.[key] !== undefined) el.placeholder = i18n[lang][key];
  });
}

const _lang = localStorage.getItem("lang") || "kk";
localStorage.setItem("lang", _lang);

window.goLang = _lang;
window.goI18n = i18n;

const _sel = document.getElementById("langSelect");
if (_sel) {
  _sel.value = _lang;
  _sel.onchange = e => {
    localStorage.setItem("lang", e.target.value);
    location.reload();
  };
}

applyLang(_lang);

// Backward compat for my-courses.html
const texts = { kk: { courses: i18n.kk.courses }, ru: { courses: i18n.ru.courses } };
const _coursesEl = document.getElementById("coursesTitle");
if (_coursesEl) _coursesEl.innerText = i18n[_lang].courses;
